version: v1.0
name: Prod Test 1
agent:
  machine:
    type: s1-prod-ubuntu24-04-arm64-1
blocks:
  - name: 'prod-test'
    task:
      jobs:
        - name: 'prod-test'
          commands:
            - sleep 1

