version: v1.0
name: Prod global resources test
agent:
  machine:
    type: s1-prod-ubuntu24-04-arm64-1
blocks:
  - name: 'prod-global-resources-test'
    task:
      jobs:
        - name: 'prod-global-resources-test'
          commands:
            - sleep 2

