version: v1.0
name: Prod deploy 1
agent:
  machine:
    type: s1-prod-ubuntu24-04-arm64-1
blocks:
  - name: 'prod-deploy-1'
    task:
      jobs:
        - name: 'prod-deploy-1'
          commands:
            - sleep 2

